workflows:
  ios-build:
    name: iOS Build Workflow
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          flutter pub get
      - name: Build iOS (no code sign)
        script: |
          flutter build ios --release --no-codesign
      - name: Package .ipa manually
        script: |
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/
          zip -r Runner.ipa Payload
    artifacts:
      - Runner.ipa
