name: hayami_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  image_picker: ^1.1.2
  rename: ^3.1.0
  shared_preferences: ^2.5.3
  printing: ^5.14.2
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.3.0
  flutter_launcher_icons: ^0.13.1  # <-- Tambahkan ini

flutter:
  uses-material-design: true

  assets:
    #- images/kledo.png
    - assets/image/hayamibaru.png
    - assets/image/hayamilogo.png


flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/hayamibaru.png"
